#!/usr/bin/env python3
"""
OpenClaw Travel Agent – Interactive Setup Wizard.

Run: python scripts/setup.py

Steps:
  1. Groq API key
  2. Enable/configure providers
  3. Telegram bot token
  4. Provide Midtrans Server Key (for payments)
  5. Redis + PostgreSQL URLs

File: scripts/setup.py
"""
import os
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
ENV_FILE = ROOT / ".env"
PROVIDERS_YAML = ROOT / "config" / "providers.yaml"


def banner():
    print("\n" + "=" * 56)
    print("  🌏  OpenClaw Travel Agent – Setup Wizard")
    print("=" * 56 + "\n")


def prompt(msg: str, default: str = "", secret: bool = False) -> str:
    display = f" [{default}]" if default else ""
    if secret:
        import getpass
        val = getpass.getpass(f"  {msg}{display}: ").strip()
    else:
        val = input(f"  {msg}{display}: ").strip()
    return val or default


def yes_no(msg: str, default: bool = True) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    val = input(f"  {msg}{suffix}: ").strip().lower()
    if not val:
        return default
    return val in ("y", "yes")


def write_env(config: dict):
    lines = ["# OpenClaw Travel Agent – auto-generated by setup.py\n"]
    for k, v in config.items():
        lines.append(f"{k}={v}\n")
    ENV_FILE.write_text("".join(lines))
    print(f"\n  ✅ .env written to {ENV_FILE}")


def main():
    banner()
    config = {}

    # ── Step 1: Groq ──────────────────────────────────────────────────────
    print("── 1/5  Groq LLM ────────────────────────────────────────────")
    print("  Get a free key at https://console.groq.com")
    config["GROQ_API_KEY"] = prompt("Groq API key", secret=True)
    config["GROQ_MODEL"] = prompt("Groq model", default="llama-3.3-70b-versatile")
    print()

    # ── Step 2: Providers ─────────────────────────────────────────────────
    print("── 2/5  Provider API keys (leave blank to use mock/scraper) ─")
    provider_keys = {
        "TIKET_API_KEY": "Tiket.com API key",
        "AMADEUS_CLIENT_ID": "Amadeus client ID",
        "AMADEUS_CLIENT_SECRET": "Amadeus client secret",
        "KIWI_API_KEY": "Kiwi (Tequila) API key",
        "SKYSCANNER_API_KEY": "Skyscanner API key",
        "LITEAPI_KEY": "LiteAPI key",
        "BOOKING_CLIENT_ID": "Booking.com client ID",
        "BOOKING_CLIENT_SECRET": "Booking.com client secret",
    }
    for env_key, label in provider_keys.items():
        config[env_key] = prompt(label, default="")
    print()

    # ── Step 3: Telegram ──────────────────────────────────────────────────
    print("── 3/5  Telegram Bot ────────────────────────────────────────")
    print("  Create a bot at https://t.me/BotFather → /newbot")
    config["TELEGRAM_BOT_TOKEN"] = prompt("Telegram bot token", secret=True)
    print()

    # ── Step 4: Midtrans ──────────────────────────────────────────────────
    print("── 4/4  Midtrans API (Payment Gateway) ─────────────────────")
    config["MIDTRANS_SERVER_KEY"] = prompt("Midtrans Server Key (e.g., SB-Mid-server-...)", default="")
    config["MIDTRANS_IS_PRODUCTION"] = prompt("Midtrans is production?", default="false")
    print()

    # ── Step 5: Infrastructure ────────────────────────────────────────────
    print("── 5/5  Infrastructure (Redis & PostgreSQL) ─────────────────")
    config["REDIS_URL"] = prompt("Redis URL", default="redis://localhost:6379/0")
    config["DATABASE_URL"] = prompt(
        "PostgreSQL URL", default="postgresql+asyncpg://openclaw:password@localhost/openclaw"
    )
    config["LOG_LEVEL"] = prompt("Log level", default="INFO")
    config["CACHE_TTL"] = "600"
    print()

    # ── Write .env ────────────────────────────────────────────────────────
    write_env(config)

    # ── Summary ───────────────────────────────────────────────────────────
    print("\n── Setup Complete ──────────────────────────────────────────\n")
    print("  Next steps:")
    print("  1. docker-compose up --build")
    print("     OR  python -m uvicorn api.main:app --reload")
    print("  2. Open Telegram and message your bot!")
    print()
    has_groq = bool(config.get("GROQ_API_KEY"))
    has_tg = bool(config.get("TELEGRAM_BOT_TOKEN"))
    print(f"  Groq LLM:       {'✅ configured' if has_groq else '⚠️ not set – will use rule-based fallback'}")
    print(f"  Telegram bot:   {'✅ configured' if has_tg else '⚠️ not set'}")
    print(f"  Mock providers: ✅ always available as fallback\n")


if __name__ == "__main__":
    main()
